
import pandas as pd
import datetime as dt
import os

test_files = os.listdir("datasets/")
test_case_count = 0
for file in test_files:
    df = pd.read_csv("datasets/"+file)
    test_case_count += 1
    print("_____________________Test case - "+str(test_case_count)+"_________________________ ")

    #Question 1 -

    # Calculate total price per order
    df['total_price'] = df['product_price'] * df['quantity']
    #convert date string to datetime object
    df['Date'] = pd.to_datetime(df['order_date'], errors='coerce')
    # Group monthly orders and apply sum for all months
    q1 = df.groupby(df.Date.dt.month)['total_price'].sum()
    print("Question1 : Compute the total revenue generated by the online store for each month in the dataset.")
    print(q1)
    print("**************")
    # Question 2 -
    # Group by products and apply sum for all groups
    q2 = df.groupby(df.product_name)['total_price'].sum()
    print("Question2 : Compute the total revenue generated by each product in the dataset.")
    print(q2)
    print("******************")
    # Question 3 -
    # Group by customer id and apply sum for all groups
    q3 = df.groupby(df.customer_id)['total_price'].sum()
    print("Question3 : Compute the total revenue generated by each customer in the dataset.")
    print(q3)
    print("******************")
    # Question 4-
    # Groups by customer id -> apply sum for all groups -> sort groups based on total revenue -> select first 10 groups
    q4 = df.groupby(df.customer_id)['total_price'].sum().sort_values(ascending=False).head(10)
    print("Question4 : Identify the top 10 customers by revenue generated.")
    print(q4)
    print("******************")
print(df)
