name: Python-test-build-deploy-workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:

  UnitTest:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: execute script
        run: |
          cd test/
          python3 processdata.py

  Build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    needs: UnitTest
    environment: main
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - uses: docker-practice/actions-setup-docker@master
        timeout-minutes: 12
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      - name: Build and push - test docker image
        run: |
          cd test/
          docker image build -t docker0rahul/test_processdata:latest .
          docker image push docker0rahul/test_processdata:latest
      - name: Build and push - App docker image
        run: |
          docker image build -t docker0rahul/processdata:latest .
          docker image push docker0rahul/processdata:latest
          docker logout
          
  Deploy:
    name: Docker compose
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - uses: docker-practice/actions-setup-docker@master
        timeout-minutes: 12
      - name: docker compose up
        run: |
          docker-compose up | tee results.txt
      - name: Upload result artifact
        uses: actions/upload-artifact@v3
        with:
          name: Results
          path: results.txt
